export const initialTrades = [
  {
    id: "sample-1",
    date: "2026-07-01",
    market: "NASDAQ",
    symbol: "NVDA",
    direction: "Long",
    setup: "Breakout",
    session: "New York",
    bias: "Long (65/35)",
    entryTime: "09:15",
    exitTime: "09:42",
    setupRating: 4,
    criteriaBiasConfirmed: true,
    criteriaLiquidity: true,
    criteriaPullback: false,
    criteriaLimitEntry: true,
    criteriaRisk: true,
    entry: 120.5,
    exit: 124.2,
    pnl: 370.0,
    risk: 100,
    quantity: 100,
    fees: 2.5,
    notes: "Dobrá reakce po breakoutu.",
    tags: ["Momentum", "A+"],
    createdAt: "2026-07-01T09:15:00.000Z"
  },
  {
    id: "sample-2",
    date: "2026-07-02",
    market: "NYSE",
    symbol: "AAPL",
    direction: "Short",
    setup: "Pullback",
    session: "Londýn-NY",
    bias: "Short (65/35)",
    entryTime: "14:10",
    exitTime: "14:36",
    setupRating: 3,
    criteriaBiasConfirmed: true,
    criteriaLiquidity: true,
    criteriaPullback: true,
    criteriaLimitEntry: false,
    criteriaRisk: true,
    entry: 205.8,
    exit: 202.1,
    pnl: 370.0,
    risk: 90,
    quantity: 100,
    fees: 3.5,
    notes: "Nedostatečně přesný pullback.",
    tags: ["Mean reversion"],
    createdAt: "2026-07-02T14:10:00.000Z"
  },
  {
    id: "sample-3",
    date: "2026-07-03",
    market: "Forex",
    symbol: "EURUSD",
    direction: "Long",
    setup: "Trend continuation",
    session: "Londýnská",
    bias: "Neutral (50/50)",
    entryTime: "16:05",
    exitTime: "16:48",
    setupRating: 5,
    criteriaBiasConfirmed: true,
    criteriaLiquidity: false,
    criteriaPullback: true,
    criteriaLimitEntry: true,
    criteriaRisk: true,
    entry: 1.0852,
    exit: 1.0914,
    pnl: 62.0,
    risk: 120,
    quantity: 10000,
    fees: 4.0,
    notes: "Silný trend a dobré načasování.",
    tags: ["Trend", "Execution"],
    createdAt: "2026-07-03T16:05:00.000Z"
  }
];
